spring:
  mvc:
    enable-global-res: true
  application:
    name: user-consumer
  main:
    allow-bean-definition-overriding: true
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  metadata-report:
    address: ${dubbo.registry.address}
  application:
    name: ${spring.application.name}
    register-mode: instance
    register-consumer: false
  protocol:
    port: -1
    serialization: hessian2
  provider:
    loadbalance: shortestresponse
  consumer:
    loadbalance: shortestresponse
    check: false
server:
  port: 8081